// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package api

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// NebulaClient is the client API for Nebula service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type NebulaClient interface {
	AddNamespace(ctx context.Context, in *AddDeploymentReq, opts ...grpc.CallOption) (*AddDeploymentResp, error)
}

type nebulaClient struct {
	cc grpc.ClientConnInterface
}

func NewNebulaClient(cc grpc.ClientConnInterface) NebulaClient {
	return &nebulaClient{cc}
}

func (c *nebulaClient) AddNamespace(ctx context.Context, in *AddDeploymentReq, opts ...grpc.CallOption) (*AddDeploymentResp, error) {
	out := new(AddDeploymentResp)
	err := c.cc.Invoke(ctx, "/proto.Nebula/AddNamespace", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// NebulaServer is the server API for Nebula service.
// All implementations must embed UnimplementedNebulaServer
// for forward compatibility
type NebulaServer interface {
	AddNamespace(context.Context, *AddDeploymentReq) (*AddDeploymentResp, error)
	mustEmbedUnimplementedNebulaServer()
}

// UnimplementedNebulaServer must be embedded to have forward compatible implementations.
type UnimplementedNebulaServer struct {
}

func (UnimplementedNebulaServer) AddNamespace(context.Context, *AddDeploymentReq) (*AddDeploymentResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddNamespace not implemented")
}
func (UnimplementedNebulaServer) mustEmbedUnimplementedNebulaServer() {}

// UnsafeNebulaServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to NebulaServer will
// result in compilation errors.
type UnsafeNebulaServer interface {
	mustEmbedUnimplementedNebulaServer()
}

func RegisterNebulaServer(s grpc.ServiceRegistrar, srv NebulaServer) {
	s.RegisterService(&Nebula_ServiceDesc, srv)
}

func _Nebula_AddNamespace_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddDeploymentReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NebulaServer).AddNamespace(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Nebula/AddNamespace",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NebulaServer).AddNamespace(ctx, req.(*AddDeploymentReq))
	}
	return interceptor(ctx, in, info, handler)
}

// Nebula_ServiceDesc is the grpc.ServiceDesc for Nebula service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Nebula_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.Nebula",
	HandlerType: (*NebulaServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AddNamespace",
			Handler:    _Nebula_AddNamespace_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "nebula.proto",
}
